-- Agendamento v2: mensagens com a hora exata da diária ({{horario}} = "das 08:30 às 12:30") no lugar do turno ({{periodo}}).
-- Versão nova (a atual + 1) de cada template afetado, ativa; a anterior fica no histórico (restaurável pelo painel).
-- Gerado a partir de src/automacoes/catalogo.js (testa-aut-homolog confere banco = catálogo).
update public.templates set ativo = false where codigo = 'lembrete_vespera' and canal = 'whatsapp' and ativo;
insert into public.templates (codigo, canal, versao, corpo, assunto, variaveis_permitidas, variaveis_obrigatorias, categoria_meta, ativo) select 'lembrete_vespera', 'whatsapp', coalesce(max(versao), 0) + 1, 'Oi, {{nome}}! Passando pra lembrar: {{quando}} tem atendimento da Prime {{horario}}, com {{carga}}. O material de limpeza é seu; para área externa, deixe uma mangueira disponível. Se precisar mudar algo, responda esta mensagem.', null, array['nome', 'quando', 'horario', 'carga']::text[], array['nome', 'quando', 'horario', 'carga']::text[], 'UTILITY', true from public.templates where codigo = 'lembrete_vespera' and canal = 'whatsapp';
update public.templates set ativo = false where codigo = 'lembrete_vespera' and canal = 'email' and ativo;
insert into public.templates (codigo, canal, versao, corpo, assunto, variaveis_permitidas, variaveis_obrigatorias, categoria_meta, ativo) select 'lembrete_vespera', 'email', coalesce(max(versao), 0) + 1, 'Oi, {{nome}}! Passando pra lembrar: {{quando}} tem atendimento da Prime {{horario}}, com {{carga}}. O material de limpeza é seu; para área externa, deixe uma mangueira disponível. Se precisar mudar algo, responda esta mensagem.', 'Lembrete do seu atendimento Prime', array['nome', 'quando', 'horario', 'carga']::text[], array['nome', 'quando', 'horario', 'carga']::text[], null, true from public.templates where codigo = 'lembrete_vespera' and canal = 'email';
update public.templates set ativo = false where codigo = 'remarcacao_confirmada' and canal = 'whatsapp' and ativo;
insert into public.templates (codigo, canal, versao, corpo, assunto, variaveis_permitidas, variaveis_obrigatorias, categoria_meta, ativo) select 'remarcacao_confirmada', 'whatsapp', coalesce(max(versao), 0) + 1, 'Oi, {{nome}}. Seu atendimento foi remarcado para {{quando}}, {{horario}}. Se precisar de outro ajuste, responda esta mensagem.', null, array['nome', 'quando', 'horario']::text[], array['nome', 'quando', 'horario']::text[], 'UTILITY', true from public.templates where codigo = 'remarcacao_confirmada' and canal = 'whatsapp';
update public.templates set ativo = false where codigo = 'remarcacao_confirmada' and canal = 'email' and ativo;
insert into public.templates (codigo, canal, versao, corpo, assunto, variaveis_permitidas, variaveis_obrigatorias, categoria_meta, ativo) select 'remarcacao_confirmada', 'email', coalesce(max(versao), 0) + 1, 'Oi, {{nome}}. Seu atendimento foi remarcado para {{quando}}, {{horario}}. Se precisar de outro ajuste, responda esta mensagem.', 'Atendimento remarcado', array['nome', 'quando', 'horario']::text[], array['nome', 'quando', 'horario']::text[], null, true from public.templates where codigo = 'remarcacao_confirmada' and canal = 'email';
update public.templates set ativo = false where codigo = 'diaria_designada' and canal = 'whatsapp' and ativo;
insert into public.templates (codigo, canal, versao, corpo, assunto, variaveis_permitidas, variaveis_obrigatorias, categoria_meta, ativo) select 'diaria_designada', 'whatsapp', coalesce(max(versao), 0) + 1, 'Oi, {{nome}}! Você tem uma diária confirmada: {{data}}, {{horario}}. Endereço: {{endereco}}. Qualquer dúvida, responda esta mensagem.', null, array['nome', 'data', 'horario', 'endereco']::text[], array['nome', 'data', 'horario', 'endereco']::text[], 'UTILITY', true from public.templates where codigo = 'diaria_designada' and canal = 'whatsapp';
update public.templates set ativo = false where codigo = 'diaria_designada' and canal = 'email' and ativo;
insert into public.templates (codigo, canal, versao, corpo, assunto, variaveis_permitidas, variaveis_obrigatorias, categoria_meta, ativo) select 'diaria_designada', 'email', coalesce(max(versao), 0) + 1, 'Oi, {{nome}}! Você tem uma diária confirmada: {{data}}, {{horario}}. Endereço: {{endereco}}. Qualquer dúvida, responda esta mensagem.', 'Nova diária confirmada', array['nome', 'data', 'horario', 'endereco']::text[], array['nome', 'data', 'horario', 'endereco']::text[], null, true from public.templates where codigo = 'diaria_designada' and canal = 'email';
update public.templates set ativo = false where codigo = 'lembrete_vespera_profissional' and canal = 'whatsapp' and ativo;
insert into public.templates (codigo, canal, versao, corpo, assunto, variaveis_permitidas, variaveis_obrigatorias, categoria_meta, ativo) select 'lembrete_vespera_profissional', 'whatsapp', coalesce(max(versao), 0) + 1, 'Oi, {{nome}}. Lembrete: {{quando}} você tem diária {{horario}}. Endereço: {{endereco}}. Bom trabalho!', null, array['nome', 'quando', 'horario', 'endereco']::text[], array['nome', 'quando', 'horario', 'endereco']::text[], 'UTILITY', true from public.templates where codigo = 'lembrete_vespera_profissional' and canal = 'whatsapp';
update public.templates set ativo = false where codigo = 'lembrete_vespera_profissional' and canal = 'email' and ativo;
insert into public.templates (codigo, canal, versao, corpo, assunto, variaveis_permitidas, variaveis_obrigatorias, categoria_meta, ativo) select 'lembrete_vespera_profissional', 'email', coalesce(max(versao), 0) + 1, 'Oi, {{nome}}. Lembrete: {{quando}} você tem diária {{horario}}. Endereço: {{endereco}}. Bom trabalho!', 'Lembrete da sua próxima diária', array['nome', 'quando', 'horario', 'endereco']::text[], array['nome', 'quando', 'horario', 'endereco']::text[], null, true from public.templates where codigo = 'lembrete_vespera_profissional' and canal = 'email';
update public.templates set ativo = false where codigo = 'lembrete_checkin' and canal = 'whatsapp' and ativo;
insert into public.templates (codigo, canal, versao, corpo, assunto, variaveis_permitidas, variaveis_obrigatorias, categoria_meta, ativo) select 'lembrete_checkin', 'whatsapp', coalesce(max(versao), 0) + 1, 'Oi, {{nome}}. A diária de hoje, {{horario}}, ainda está sem check-in. Se já chegou, avise pela sua agenda; se teve imprevisto, responda esta mensagem.', null, array['nome', 'horario']::text[], array['nome', 'horario']::text[], 'UTILITY', true from public.templates where codigo = 'lembrete_checkin' and canal = 'whatsapp';
update public.templates set ativo = false where codigo = 'lembrete_checkin' and canal = 'email' and ativo;
insert into public.templates (codigo, canal, versao, corpo, assunto, variaveis_permitidas, variaveis_obrigatorias, categoria_meta, ativo) select 'lembrete_checkin', 'email', coalesce(max(versao), 0) + 1, 'Oi, {{nome}}. A diária de hoje, {{horario}}, ainda está sem check-in. Se já chegou, avise pela sua agenda; se teve imprevisto, responda esta mensagem.', 'Check-in da diária de hoje', array['nome', 'horario']::text[], array['nome', 'horario']::text[], null, true from public.templates where codigo = 'lembrete_checkin' and canal = 'email';
update public.templates set ativo = false where codigo = 'diaria_cancelada_ou_remarcada' and canal = 'whatsapp' and ativo;
insert into public.templates (codigo, canal, versao, corpo, assunto, variaveis_permitidas, variaveis_obrigatorias, categoria_meta, ativo) select 'diaria_cancelada_ou_remarcada', 'whatsapp', coalesce(max(versao), 0) + 1, 'Oi, {{nome}}. A diária de {{data}}, {{horario}}, {{oque}} e saiu da sua agenda. Qualquer dúvida, responda esta mensagem.', null, array['nome', 'data', 'horario', 'oque']::text[], array['nome', 'data', 'horario', 'oque']::text[], 'UTILITY', true from public.templates where codigo = 'diaria_cancelada_ou_remarcada' and canal = 'whatsapp';
update public.templates set ativo = false where codigo = 'diaria_cancelada_ou_remarcada' and canal = 'email' and ativo;
insert into public.templates (codigo, canal, versao, corpo, assunto, variaveis_permitidas, variaveis_obrigatorias, categoria_meta, ativo) select 'diaria_cancelada_ou_remarcada', 'email', coalesce(max(versao), 0) + 1, 'Oi, {{nome}}. A diária de {{data}}, {{horario}}, {{oque}} e saiu da sua agenda. Qualquer dúvida, responda esta mensagem.', 'Mudança na sua agenda', array['nome', 'data', 'horario', 'oque']::text[], array['nome', 'data', 'horario', 'oque']::text[], null, true from public.templates where codigo = 'diaria_cancelada_ou_remarcada' and canal = 'email';
update public.templates set ativo = false where codigo = 'checkin_atrasado' and canal = 'painel' and ativo;
insert into public.templates (codigo, canal, versao, corpo, assunto, variaveis_permitidas, variaveis_obrigatorias, categoria_meta, ativo) select 'checkin_atrasado', 'painel', coalesce(max(versao), 0) + 1, 'Diária de {{cliente}} ({{horario}}) sem check-in da profissional {{profissional}}. Falar com ela.', null, array['cliente', 'horario', 'profissional']::text[], array['cliente', 'horario', 'profissional']::text[], null, true from public.templates where codigo = 'checkin_atrasado' and canal = 'painel';
update public.automacao_regras set descricao = 'Sem check-in 30 minutos depois do horário de início' where codigo = 'D06';
