-- GERADO por scripts/gera-seed-config.mjs a partir de src/config/precos.js. Não editar à mão.
-- Mudança de preço depois do go-live: nova linha em public.precos (vigente_desde), pela RPC da Prime.
insert into public.precos (vigente_desde, tabela) values ('2026-01-01T00:00:00Z', '{"PRECOS":{"duracoes":{"2":{"centavos":13800,"metragemMaxima":30},"4":{"centavos":17500},"6":{"centavos":20300},"8":{"centavos":22000}},"horaExtraCentavos":3000,"horasExtrasMaximo":4,"metragem":{"minimo":10,"maximo":1000},"recomendacaoPorMetragem":[{"ate":50,"horas":4},{"ate":80,"horas":6},{"ate":120,"horas":8}],"avisoTempo":"Vidros, geladeira, armários internos e revestimentos exigem mais tempo.","tiposServico":{"residencial":{"nome":"Limpeza residencial","centavos":0},"empresarial":{"nome":"Limpeza empresarial ou comercial","centavos":1000},"condominial":{"nome":"Limpeza condominial","centavos":1000},"pre_pos_mudanca":{"nome":"Pré ou pós-mudança","centavos":2000},"pre_pos_evento":{"nome":"Pré ou pós-evento","centavos":2000},"passadoria":{"nome":"Passadoria de roupas (serviço exclusivo)","centavos":0,"exclusivo":true}},"naoOferecidos":{"pos_obra":"No momento não realizamos limpeza pós-obra."},"passadoriaCombinada":{"centavos":5500,"aviso":"A passadoria combinada é para pouca demanda, dentro das mesmas horas da limpeza."},"recomendacaoPassadoria":[{"ate":15,"horas":2,"descricao":"até 15 peças básicas"},{"ate":25,"horas":4,"descricao":"até 25 peças básicas e sociais leves"},{"ate":40,"horas":6,"descricao":"até 40 peças mistas"},{"ate":60,"horas":8,"descricao":"até 60 peças ou peças sociais elaboradas"}],"avisoPassadoria":"Peças delicadas ou muito amarrotadas exigem mais tempo.","taxaSabadoFeriadoCentavos":2000,"taxaSemLocalAlmocoCentavos":2500,"descontoMensal":[{"minimoDiarias":5,"centavos":4000},{"minimoDiarias":3,"centavos":2000}],"quantidadeDiarias":{"minimo":1,"maximo":12}},"cobrancaRestante":"por_atendimento","prazoRestante":"no_dia","diasBloqueados":[0],"regrasCalendario":{"antecedenciaMinimaDias":1,"horizonteMaximoDias":120,"buscaDeslocamentoMaxDias":7},"regrasNotificacao":{"fuso":"America/Sao_Paulo","horaLembreteVespera":18,"minutosAposFinalizado":120},"regioesDiarista":["BH - Centro-Sul","BH - Pampulha","BH - Oeste","BH - Barreiro","BH - Noroeste","BH - Norte","BH - Nordeste","BH - Leste","BH - Venda Nova","Contagem","Santa Luzia","Ribeirão das Neves","Sabará","Betim","Ibirité","Vespasiano","Nova Lima"]}'::jsonb);
insert into public.regioes (cidade, uf, taxa_centavos, sob_consulta) values ('Belo Horizonte', 'MG', 0, false);
insert into public.regioes (cidade, uf, taxa_centavos, sob_consulta) values ('Contagem', 'MG', 1000, false);
insert into public.regioes (cidade, uf, taxa_centavos, sob_consulta) values ('Santa Luzia', 'MG', 1000, false);
insert into public.regioes (cidade, uf, taxa_centavos, sob_consulta) values ('Ribeirão das Neves', 'MG', 1000, false);
insert into public.regioes (cidade, uf, taxa_centavos, sob_consulta) values ('Sabará', 'MG', 1000, false);
insert into public.regioes (cidade, uf, taxa_centavos, sob_consulta) values ('Betim', 'MG', 1500, false);
insert into public.regioes (cidade, uf, taxa_centavos, sob_consulta) values ('Ibirité', 'MG', 1500, false);
insert into public.regioes (cidade, uf, taxa_centavos, sob_consulta) values ('Vespasiano', 'MG', 1500, false);
insert into public.regioes (cidade, uf, taxa_centavos, sob_consulta) values ('Nova Lima', 'MG', null, true);
insert into public.feriados (data, bloqueia) values ('2026-01-01', false);
insert into public.feriados (data, bloqueia) values ('2026-02-16', false);
insert into public.feriados (data, bloqueia) values ('2026-02-17', false);
insert into public.feriados (data, bloqueia) values ('2026-04-03', false);
insert into public.feriados (data, bloqueia) values ('2026-04-21', false);
insert into public.feriados (data, bloqueia) values ('2026-05-01', false);
insert into public.feriados (data, bloqueia) values ('2026-06-04', false);
insert into public.feriados (data, bloqueia) values ('2026-08-15', false);
insert into public.feriados (data, bloqueia) values ('2026-09-07', false);
insert into public.feriados (data, bloqueia) values ('2026-10-12', false);
insert into public.feriados (data, bloqueia) values ('2026-11-02', false);
insert into public.feriados (data, bloqueia) values ('2026-11-15', false);
insert into public.feriados (data, bloqueia) values ('2026-11-20', false);
insert into public.feriados (data, bloqueia) values ('2026-12-08', false);
insert into public.feriados (data, bloqueia) values ('2026-12-25', false);
insert into public.feriados (data, bloqueia) values ('2027-01-01', false);
insert into public.feriados (data, bloqueia) values ('2027-02-08', false);
insert into public.feriados (data, bloqueia) values ('2027-02-09', false);
insert into public.feriados (data, bloqueia) values ('2027-03-26', false);
insert into public.feriados (data, bloqueia) values ('2027-04-21', false);
insert into public.feriados (data, bloqueia) values ('2027-05-01', false);
insert into public.feriados (data, bloqueia) values ('2027-05-27', false);
insert into public.feriados (data, bloqueia) values ('2027-08-15', false);
insert into public.feriados (data, bloqueia) values ('2027-09-07', false);
insert into public.feriados (data, bloqueia) values ('2027-10-12', false);
insert into public.feriados (data, bloqueia) values ('2027-11-02', false);
insert into public.feriados (data, bloqueia) values ('2027-11-15', false);
insert into public.feriados (data, bloqueia) values ('2027-11-20', false);
insert into public.feriados (data, bloqueia) values ('2027-12-08', false);
insert into public.feriados (data, bloqueia) values ('2027-12-25', false);
insert into public.configuracao (chave, valor) values ('pix', '{"chave":"123e4567-e12b-12d1-a456-426655440000","nomeRecebedor":"Prime Limpeza Teste","cidadeRecebedor":"Belo Horizonte","ficticio":true}'::jsonb);
